// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.724
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"github.com/myrjola/sheerluck/internal/contexthelpers"
)

func QuestionPeople(chatResponses []ChatResponse) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<h2 class=\"mb-1 text-lg font-bold\">Question people</h2><div id=\"answers\" class=\"mx-auto max-w-md [overflow-anchor:none]\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ChatResponses(chatResponses).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><form action=\"/question-target\" method=\"post\" hx-swap=\"beforeend show:none\" hx-target=\"#answers\" hx-push-url=\"false\" hx-form-reset-on-success class=\"mx-auto max-w-md\"><input type=\"hidden\" name=\"csrf_token\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(contexthelpers.CSRFToken(ctx))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/components/questionpeople.templ`, Line: 21, Col: 78}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"><div class=\"flex flex-col gap-2\"><label for=\"question\" class=\"block text-md font-medium leading-6 text-white\">Detective:</label><div class=\"flex rounded-md\"><div class=\"isolate flex flex-1 items-stretch focus-within:z-10\"><input name=\"question\" type=\"text\" id=\"question\" class=\"block w-full rounded-none rounded-l-md border-0 py-1.5 pl-1.5 bg-white/5 ring-1 ring-inset ring-white/50 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-500 leading-8\"></div><button type=\"submit\" hx-disabled-elt=\"this\" class=\"relative -ml-px inline-flex items-center gap-x-1.5 rounded-r-md px-3 py-2 bg-white/5 ring-1 ring-inset ring-white/50 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-500 hover:bg-white/7 hover:cursor-pointer\"><img class=\"h-6 w-auto\" src=\"/images/talk.svg\" alt=\"\"> Ask</button></div></div></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
