// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type Case struct {
	ID     string
	Name   string
	Author string
}

type Clue struct {
	ID                    string
	Description           string
	Keywords              string
	InvestigationTargetID string
}

type Completion struct {
	ID                    int64
	Order                 int64
	Question              string
	Answer                string
	UserID                []byte
	InvestigationTargetID string
}

type Credential struct {
	ID                        []byte
	PublicKey                 []byte
	AttestationType           string
	Transport                 string
	FlagUserPresent           int64
	FlagUserVerified          int64
	FlagBackupEligible        int64
	FlagBackupState           int64
	AuthenticatorAaguid       []byte
	AuthenticatorSignCount    int64
	AuthenticatorCloneWarning int64
	AuthenticatorAttachment   string
	Created                   string
	Updated                   string
	UserID                    []byte
}

type InvestigationTarget struct {
	ID        string
	Name      string
	ShortName string
	Type      string
	ImagePath string
	CaseID    string
}

type Session struct {
	Token  string
	Data   []byte
	Expiry float64
}

type User struct {
	ID          []byte
	DisplayName string
	Created     string
	Updated     string
}
