name: Docker build and push
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize, closed]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_REGION: arn
  FLY_ORG: personal
  DOCKER_REGISTRY: registry.fly.io
  DOCKER_TAG: sheerluck:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Cross-compile
        env:
          CGO_ENABLED: 1
          GOOS: linux
          GOARCH: amd64
        run: go build -ldflags='-s -w -extldflags "-static"' -o build/sheerluck ./cmd/web

      - name: Login to Fly Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.fly.io
          username: x
          password: ${{ env.FLY_API_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_TAG }}
