name: Deploy Review App
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_REGION: arn
  FLY_ORG: personal
  FLY_APP_NAME: ${{ github.actor }}-sheerluck-pr-${{ github.event.number }}

jobs:
  build_and_push:
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      docker_tag: ${{ github.sha }}
      fly_app: ${{ env.FLY_APP_NAME }}
    secrets: inherit

  review_app:
    runs-on: ubuntu-latest
    needs: [build_and_push]
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    concurrency:
      group: pr-${{ github.event.number }}

    environment:
      name: pr-${{ github.event.number }}
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Deploy PR app to Fly.io
        id: deploy
        uses: superfly/fly-pr-review-apps@1.3.0
        with:
          name: ${{ env.FLY_APP_NAME }}
          image: ${{ needs.build_and_push.outputs.docker_image_uri }}
          secrets: "LITESTREAM_REPLICA_PATH=/data/backup"
