name: Pull Request Build

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: actions/cache@v4
        with:
          path: custom-gcl
          key: ${{ runner.os }}-custom-gcl-${{ hashFiles('go.mod', '.custom-gcl.yml') }}

      - name: Build
        run: make ci

      - name: Install Litestream
        run: |
          wget https://github.com/benbjohnson/litestream/releases/download/v0.3.13/litestream-v0.3.13-linux-amd64.deb
          sudo dpkg -i litestream-v0.3.13-linux-amd64.deb

      - name: Run migrations against production database
        env:
          LITESTREAM_REPLICA_TYPE: s3
          SHEERLUCK_SQLITE_URL: restored.sqlite3
          AWS_ACCESS_KEY_ID: ${{ secrets.MIGRATIONTEST_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MIGRATIONTEST_AWS_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL_S3: https://fly.storage.tigris.dev
          AWS_ENDPOINT_URL_IAM: https://fly.iam.storage.tigris.dev
          AWS_REGION: auto
          BUCKET_NAME: sheerluck-backup
        run: make migratetest
